#!/usr/bin/python

import os,time,string,sys,commands,getpass,cgi

print "Content-type:text/html"
print ""

data=cgi.FieldStorage()

ip_namenode=data.getvalue('ip_namenode')

data_uri = open('hadoop.jpg', 'rb').read().encode('base64').replace('\n', '')
#img_tag = '<img src="data:image/jpg;base64,%s">' % data_uri


data_uri2 = open('refresh.jpg', 'rb').read().encode('base64').replace('\n', '')

print '<div style="background-color:#FFDAB9; background-size:4100px;background-repeat:repeat; width:2000px;">'


print "<h1 style='margin:0px; color:yellow;background-color:#D2691E; text-align:center; font-family:verdana; height:50px; width:2000px; background-image:url(data:image/jpg;base64,%s);background-size:170px;background-repeat: no-repeat; postion:fixed; padding:40px 40px;' title='Hadoop'> " % data_uri 
print "Hadoop"
print "</h1>"


print "<ul>"
print "<li style='margin:0px; display: block; color: white;text-align: center;padding: 14px 16px;text-decoration: none; width:1000px; background-color:#6495ED;'>Status of HDFS Cluster</li>"
print "</ul>"

cluster_details=commands.getoutput("sudo hadoop dfsadmin -report")
print "<pre>"
print "<font style='color:#D2691E;' size='4'>"
print "<i>"
print cluster_details
print "</i>"
print "</font>"
print "</pre>"

print "<br>"
print "<a href='dfsadmin_report'>"
print "<img src='data:image/jpg;base64,%s' style='width:100px; height:100px; margin-left:560px;'>" % data_uri2
print "</a>"
print "<br>"
print "<br>"
print "</div>"


